### ISSUE TITLE
ACM Tracker

### ISSUE THREAD

**Issue by wencheng256** [JudasDie/Comparison#4]
Hello, ACM tracker has reported its results on LaSOT in origin paper, it's 0.572 of success.  Thank you for your work!

**Comment by wencheng256** [comment]
And another issue UAV result of TransT is wrong, it should be 69.1

**Comment by Kingzerd** [comment]
Very thanks for your addition and correction!

**Comment by JudasDie** [comment]
Thanks for the notice. The correction has been done!
